package bind

import (
	"fmt"
	"go/format"
	"strings"
)

// Generate renders m into a single, complete, gofmt-clean Go source
// file. format.Source (the same engine `gofmt` itself uses) runs on the
// final output before returning — a real syntax bug in this generator
// surfaces immediately as an error here, never as invalid Go silently
// written to disk.
func (m *Model) Generate() (string, error) {
	var b strings.Builder

	fmt.Fprintf(&b, "// Code generated by `vmnet bind` from %s. DO NOT EDIT.\n", m.SourceName)
	fmt.Fprintf(&b, "//\n")
	fmt.Fprintf(&b, "// Every generated method whose real .NET signature vmnet.bind could map\n")
	fmt.Fprintf(&b, "// precisely (primitive parameter/return types, or another type this same\n")
	fmt.Fprintf(&b, "// run also binds) gets one; a real, overloaded, or otherwise-unmappable\n")
	fmt.Fprintf(&b, "// member still gets a real, callable Go entry point — just a more general\n")
	fmt.Fprintf(&b, "// one (raw ...vmnet.Value arguments) — noted in its own doc comment below.\n")
	fmt.Fprintf(&b, "// See docs/en/api-stability.md for vmnet's own frozen public Value API this\n")
	fmt.Fprintf(&b, "// generated code is built on.\n")
	fmt.Fprintf(&b, "package %s\n\n", m.GoPackage)
	fmt.Fprintf(&b, "import (\n\tvmnet \"github.com/arturoeanton/go-vmnet\"\n)\n\n")

	if len(m.Types) == 0 {
		fmt.Fprintf(&b, "// No public, top-level class or struct was found to bind — nothing to generate.\n")
	}

	for _, bt := range m.Types {
		writeType(&b, bt)
	}

	if usesBool(m) {
		fmt.Fprintf(&b, "// boolToI32 converts a Go bool to the 0/1 vmnet.Int32 shape every real\n")
		fmt.Fprintf(&b, "// C# bool parameter compiles to on the CIL evaluation stack (spec §17.1:\n")
		fmt.Fprintf(&b, "// vmnet has no distinct bool Kind — bool/char/byte/short are all the same\n")
		fmt.Fprintf(&b, "// KindI4 a plain int32 is).\n")
		fmt.Fprintf(&b, "func boolToI32(v bool) int32 {\n\tif v {\n\t\treturn 1\n\t}\n\treturn 0\n}\n\n")
	}

	src := b.String()
	formatted, err := format.Source([]byte(src))
	if err != nil {
		return "", fmt.Errorf("bind: generated Go source is invalid (this is a bug in the generator, not in %s): %w\n\n%s", m.SourceName, err, src)
	}
	return string(formatted), nil
}

// usesBool reports whether any bound method/ctor across m has a bool
// PARAMETER — the only shape that needs the generated boolToI32 helper
// (a bool RETURN value unwraps via a plain `!= 0` comparison, no helper
// call needed).
func usesBool(m *Model) bool {
	hasBoolParam := func(bm *BoundMethod) bool {
		if bm == nil {
			return false
		}
		for _, p := range bm.Params {
			if p.Type.Kind == "bool" {
				return true
			}
		}
		return false
	}
	for _, bt := range m.Types {
		for _, bm := range bt.Ctors {
			if hasBoolParam(bm) {
				return true
			}
		}
		for _, bm := range bt.Instance {
			if hasBoolParam(bm) {
				return true
			}
		}
		for _, bm := range bt.Static {
			if hasBoolParam(bm) {
				return true
			}
		}
	}
	return false
}

func writeType(b *strings.Builder, bt *BoundType) {
	kind := "class"
	if bt.IsValue {
		kind = "struct"
	}
	fmt.Fprintf(b, "// %s wraps the real %s %s %s.\n", bt.GoName, bt.FullName, kind, describeMemberCounts(bt))
	fmt.Fprintf(b, "type %s struct {\n\tinstance *vmnet.Instance\n}\n\n", bt.GoName)

	fmt.Fprintf(b, "// %sTypeFullName is %s's own real \"Namespace.Type\" name, as vmnet's\n", bt.GoName, bt.GoName)
	fmt.Fprintf(b, "// metadata layer names it — the string every generated call site below\n")
	fmt.Fprintf(b, "// passes to Assembly.Call/Assembly.New under the hood.\n")
	fmt.Fprintf(b, "const %sTypeFullName = %q\n\n", bt.GoName, bt.FullName)

	fmt.Fprintf(b, "// %sFrom wraps an already-constructed %s instance (e.g. one returned by\n", bt.GoName, bt.FullName)
	fmt.Fprintf(b, "// another generated method) without calling its constructor again.\n")
	fmt.Fprintf(b, "func %sFrom(instance *vmnet.Instance) *%s {\n\treturn &%s{instance: instance}\n}\n\n", bt.GoName, bt.GoName, bt.GoName)

	fmt.Fprintf(b, "// Instance returns the underlying *vmnet.Instance — use it directly for\n")
	fmt.Fprintf(b, "// anything this generated wrapper doesn't cover.\n")
	fmt.Fprintf(b, "func (r *%s) Instance() *vmnet.Instance { return r.instance }\n\n", bt.GoName)

	if len(bt.Ctors) == 1 {
		writeCtor(b, bt, bt.Ctors[0])
	}

	for _, bm := range bt.Instance {
		writeInstanceMethod(b, bt, bm)
	}
	for _, bm := range bt.Static {
		writeStaticMethod(b, bt, bm)
	}
}

func describeMemberCounts(bt *BoundType) string {
	return fmt.Sprintf("(%d instance method(s), %d static method(s))", len(bt.Instance), len(bt.Static))
}

func writeCtor(b *strings.Builder, bt *BoundType, ctor *BoundMethod) {
	fmt.Fprintf(b, "// New%s constructs a new %s.\n", bt.GoName, bt.FullName)
	if ctor.Overloaded {
		fmt.Fprintf(b, "//\n// Real %s has more than one constructor overload — vmnet can't map C#\n", bt.FullName)
		fmt.Fprintf(b, "// overloading onto a single Go signature, so this passes arguments straight\n")
		fmt.Fprintf(b, "// through to vmnet's own runtime overload resolution (picked by argument\n")
		fmt.Fprintf(b, "// count and Kind, exactly like a real overloaded call site) instead of a\n")
		fmt.Fprintf(b, "// precisely-typed signature.\n")
		fmt.Fprintf(b, "func New%s(asm *vmnet.Assembly, args ...vmnet.Value) (*%s, error) {\n", bt.GoName, bt.GoName)
		fmt.Fprintf(b, "\tinstance, err := asm.New(%sTypeFullName, args...)\n", bt.GoName)
		fmt.Fprintf(b, "\tif err != nil {\n\t\treturn nil, err\n\t}\n")
		fmt.Fprintf(b, "\treturn %sFrom(instance), nil\n}\n\n", bt.GoName)
		return
	}
	params := renderParamList(ctor.Params)
	fmt.Fprintf(b, "func New%s(asm *vmnet.Assembly%s) (*%s, error) {\n", bt.GoName, params, bt.GoName)
	fmt.Fprintf(b, "\tinstance, err := asm.New(%sTypeFullName%s)\n", bt.GoName, renderArgList(ctor.Params))
	fmt.Fprintf(b, "\tif err != nil {\n\t\treturn nil, err\n\t}\n")
	fmt.Fprintf(b, "\treturn %sFrom(instance), nil\n}\n\n", bt.GoName)
}

func writeInstanceMethod(b *strings.Builder, bt *BoundType, bm *BoundMethod) {
	fmt.Fprintf(b, "// %s calls %s.%s.\n", bm.GoName, bt.FullName, bm.Name)
	if bm.Overloaded {
		writeOverloadedInstanceMethod(b, bt, bm)
		return
	}
	params := renderParamList(bm.Params)
	args := renderArgList(bm.Params)
	if bm.Return == nil {
		fmt.Fprintf(b, "func (r *%s) %s(%s) error {\n", bt.GoName, bm.GoName, strings.TrimPrefix(params, ", "))
		fmt.Fprintf(b, "\t_, err := r.instance.Call(%q%s)\n\treturn err\n}\n\n", bm.Name, args)
		return
	}
	retType := bm.Return.GoType
	fmt.Fprintf(b, "func (r *%s) %s(%s) (%s, error) {\n", bt.GoName, bm.GoName, strings.TrimPrefix(params, ", "), retType)
	fmt.Fprintf(b, "\tresult, err := r.instance.Call(%q%s)\n", bm.Name, args)
	writeReturnUnwrap(b, *bm.Return)
	fmt.Fprintf(b, "}\n\n")
}

func writeOverloadedInstanceMethod(b *strings.Builder, bt *BoundType, bm *BoundMethod) {
	fmt.Fprintf(b, "//\n// Real %s has more than one overload sharing this name — vmnet can't map\n", bm.Name)
	fmt.Fprintf(b, "// C# overloading onto a single Go signature, so this passes arguments\n")
	fmt.Fprintf(b, "// straight through to vmnet's own runtime overload resolution instead of a\n")
	fmt.Fprintf(b, "// precisely-typed signature.\n")
	fmt.Fprintf(b, "func (r *%s) %s(args ...vmnet.Value) (vmnet.Value, error) {\n\treturn r.instance.Call(%q, args...)\n}\n\n", bt.GoName, bm.GoName, bm.Name)
}

func writeStaticMethod(b *strings.Builder, bt *BoundType, bm *BoundMethod) {
	fmt.Fprintf(b, "// %sStatic_%s calls the static method %s.%s.\n", bt.GoName, bm.GoName, bt.FullName, bm.Name)
	if bm.Overloaded {
		fmt.Fprintf(b, "//\n// Real %s.%s has more than one overload sharing this name — vmnet can't\n", bt.FullName, bm.Name)
		fmt.Fprintf(b, "// map C# overloading onto a single Go signature, so this passes arguments\n")
		fmt.Fprintf(b, "// straight through to vmnet's own runtime overload resolution instead of a\n")
		fmt.Fprintf(b, "// precisely-typed signature.\n")
		fmt.Fprintf(b, "func %sStatic_%s(asm *vmnet.Assembly, args ...vmnet.Value) (vmnet.Value, error) {\n", bt.GoName, bm.GoName)
		fmt.Fprintf(b, "\treturn asm.Call(%sTypeFullName, %q, args...)\n}\n\n", bt.GoName, bm.Name)
		return
	}
	params := renderParamList(bm.Params)
	args := renderArgList(bm.Params)
	if bm.Return == nil {
		fmt.Fprintf(b, "func %sStatic_%s(asm *vmnet.Assembly%s) error {\n", bt.GoName, bm.GoName, params)
		fmt.Fprintf(b, "\t_, err := asm.Call(%sTypeFullName, %q%s)\n\treturn err\n}\n\n", bt.GoName, bm.Name, args)
		return
	}
	retType := bm.Return.GoType
	fmt.Fprintf(b, "func %sStatic_%s(asm *vmnet.Assembly%s) (%s, error) {\n", bt.GoName, bm.GoName, params, retType)
	fmt.Fprintf(b, "\tresult, err := asm.Call(%sTypeFullName, %q%s)\n", bt.GoName, bm.Name, args)
	writeReturnUnwrap(b, *bm.Return)
	fmt.Fprintf(b, "}\n\n")
}

// writeReturnUnwrap emits the shared "check err, then unwrap result into
// the mapped Go type" tail every non-void, non-overloaded generated
// method body ends with.
func writeReturnUnwrap(b *strings.Builder, ret MappedType) {
	zero := zeroValueFor(ret)
	fmt.Fprintf(b, "\tif err != nil {\n\t\treturn %s, err\n\t}\n", zero)
	switch ret.Kind {
	case "int32":
		fmt.Fprintf(b, "\treturn result.Native().(int32), nil\n")
	case "int64":
		fmt.Fprintf(b, "\treturn result.Native().(int64), nil\n")
	case "float32":
		fmt.Fprintf(b, "\treturn result.Native().(float32), nil\n")
	case "float64":
		fmt.Fprintf(b, "\treturn result.Native().(float64), nil\n")
	case "string":
		fmt.Fprintf(b, "\treturn result.Native().(string), nil\n")
	case "bool":
		fmt.Fprintf(b, "\treturn result.Native().(int32) != 0, nil\n")
	case "bytes":
		fmt.Fprintf(b, "\treturn result.Native().([]byte), nil\n")
	case "instance":
		fmt.Fprintf(b, "\tinst, _ := result.(*vmnet.Instance)\n\treturn %sFrom(inst), nil\n", ret.BoundAs)
	default: // "generic": the natural Call/New return shape already matches.
		fmt.Fprintf(b, "\treturn result, nil\n")
	}
}

func zeroValueFor(mt MappedType) string {
	switch mt.Kind {
	case "int32", "int64", "float32", "float64":
		return "0"
	case "string":
		return `""`
	case "bool":
		return "false"
	case "bytes":
		return "nil"
	case "instance":
		return "nil"
	default:
		return "nil"
	}
}

// renderParamList renders "<vmnet.Value/Go type> paramN" for every
// parameter, with a leading ", " so a caller can splice it straight
// after another fixed argument (asm *vmnet.Assembly) or trim that
// prefix for a receiver method with no fixed leading argument.
func renderParamList(params []Param) string {
	var b strings.Builder
	for i, p := range params {
		fmt.Fprintf(&b, ", arg%d %s", i, p.Type.GoType)
	}
	return b.String()
}

// renderArgList renders ", <vmnet.Value-wrapped expression>" for every
// parameter, matching renderParamList's own argN naming 1:1.
func renderArgList(params []Param) string {
	var b strings.Builder
	for i, p := range params {
		b.WriteString(", ")
		b.WriteString(wrapArgExpr(fmt.Sprintf("arg%d", i), p.Type))
	}
	return b.String()
}

func wrapArgExpr(name string, mt MappedType) string {
	switch mt.Kind {
	case "int32":
		return "vmnet.Int32(" + name + ")"
	case "int64":
		return "vmnet.Int64(" + name + ")"
	case "float32":
		return "vmnet.Float32(" + name + ")"
	case "float64":
		return "vmnet.Float64(" + name + ")"
	case "string":
		return "vmnet.String(" + name + ")"
	case "bool":
		return "vmnet.Int32(boolToI32(" + name + "))"
	case "bytes":
		return "vmnet.ByteArray(" + name + ")"
	case "instance":
		return name + ".instance"
	default: // "generic": the parameter is already a vmnet.Value.
		return name
	}
}
